export const stabFilmData = {
  backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
  // backdrop_path: '',
  genre_ids: [28, 35, 12],
  id: 772436,
  original_title: 'Matando Cabos 2: La Máscara del Máscara',
  overview:
    'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
  //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
  poster_path: '',
  release_date: '2021-10-01',
  title: 'Matando Cabos 2',
  averageStar: 3.5,
}

export type FilmData = typeof stabFilmData

//２０件デモ
export const stabFilmDataList = [
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772438,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    poster_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772439,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772430,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772432,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 77243623,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 77243611,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7725345,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7723276,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 77267543,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7724084,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7722618,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 771,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772434356,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 771232436,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7543272436,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7724786436,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 7724875336,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772487656736,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 772431236,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
  {
    // backdrop_path: '/5UmoOvOmnCHiJj3TAKVn7uNAKAW.jpg',
    backdrop_path: '',
    genre_ids: [28, 35, 12],
    id: 1234772436,
    original_title: 'Matando Cabos 2: La Máscara del Máscara',
    overview:
      'Faced with the unexpected death of his estranged father -El Máscara- and the subsequent theft of his precious mask, Rubén -Mascarita- will find himself confronted with his past. Alongside his invincible bodyguard Tony "The Cannibal" and, an unexpected ally, he will have only one day to recover it and make amends with the memory of his father.',
    //poster_path: '/jxdKa1467pktAILLbfw6kZyQlbW.jpg',
    poster_path: '',
    release_date: '2021-10-01',
    title: 'Matando Cabos 2: La Máscara del Máscara',
    averageStar: 3.5,
  },
]
